# Generated by Django 3.2.25 on 2024-09-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(related_name='core_user', to='core.Tag'),
        ),
    ]
