# Generated by Django 3.2.25 on 2024-09-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240912_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
