# Generated by Django 3.2.25 on 2024-09-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240915_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(related_name='core_project', to='core.Project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(related_name='core_user', to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_experiences',
            field=models.ManyToManyField(related_name='core_experience', to='core.WorkExperience'),
        ),
    ]
