# Generated by Django 3.2.25 on 2024-09-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240915_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='project_technologie', to='core.Technologie'),
        ),
    ]
