# Generated by Django 3.2.25 on 2024-09-16 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_project_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologie',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
