# Generated by Django 3.2.25 on 2024-09-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_technologie_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='technologies', to='core.Technologie'),
        ),
        migrations.AlterField(
            model_name='technologie',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_technologies', to='core.project'),
        ),
    ]
