# Generated by Django 3.2.25 on 2024-09-21 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240918_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologie',
            name='project',
        ),
        migrations.AddField(
            model_name='technologie',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_technologie', to=settings.AUTH_USER_MODEL),
        ),
    ]
