# Generated by Django 3.2.25 on 2024-09-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20240926_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='post',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='name',
            field=models.CharField(default='fyp', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(related_name='posts', to='core.Hashtag'),
        ),
    ]
