# Generated by Django 3.2.25 on 2024-10-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_group_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
