# Generated by Django 3.2.25 on 2024-11-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_notification'),
        ('core', '0025_post_image'),
    ]

    operations = [
    ]
